acrolinx/platform-api

apiary.apib

I think there is a typo in word 'doen't'. It should be 'doesn't' or 'don't' or 'does not'

Fixed typo 'doen't'

---

apiary.apib

Hi,
I see that response links for CA dashboard are part of data and not directly links. In the response JSON I would prefer them to be displayed as fetched from the platform.
Please correct the formatting if incorrect, I don't have right configured tool to update documentation.
Thanks
Abhijeet

links in CA dashboard are part of data

---

apiary.apib

Due to the core server code changes because of the bug https://acrolinx.atlassian.net/browse/DEV-22432 
New error type was licenseLimitExceeded introduced.
The user will see this error if he/she will be over the limit of the named licenses for this customer.
For example if a customer bought Acrolinx with 5 licenses, 5 users are using it already and user number 6 wants to check the document.

DEV-22432 New error type licenseLimitExceeded added

---

apiary.apib

There may be other limits on the license. They will all cause the same error type.

Changed back to a generic licensing error

---

apiary.apib

According to the blueprint the field importance it's an optional field that takes "HIGH" or "NORMAL", but it actually is an optional field that takes null, and lowercase "normal" or "high", also the behaviour if the field is set to null is not documented. This PR only addresses the casing issue.

danielroca-fixes

---

apiary.apib

When creating new roles via the API it's possible to mark them as default. This `default` attribute is optional on create. By default it's `false`.
- Added request example `Create Default Role`

DEV-25732 Enrich CreateRole data structure with `default` attribute

---

apiary.apib

Added requests with response examples (200, 401, 403, 404)
- Update the entire model of a Role
- Update default attribute:
- Add role to Defaults
- Remove role from Defaults
- Renamed data structure `CreateRole` to `CreateOrUpdateRole`
- Fixed some typo

DEV-26193 Add or remove Role from default roles on update

---

apiary.apib

- Set the password length limit to 1 (Used to be 10)
- Please read JIRA ticket comments for further notes and rationale

DEV-25720 set password length limit to 1

---

apiary.apib

+ Added note about endpoint `POST /api/v1/user/self/tokens` now supporting Basic auth scheme in the `X-Acrolinx-Auth` request header.
+ Added separate request example with basic auth and with API token in the header, extra description about how to provide credentials in the header value.

DEV-25771 Allow basic auth on self create api token endpoint

---

apiary.apib

Add a new section for the `/licenses` end-point with a subsection on statistics.

DEV-22511: add licenses api group with statistics sub-section

---

apiary.apib

I've added information about how to get a paginated response for the user list and how the response is affected. I've only added two tables about added header values and links relations. I did not add another complete response example since I feel that would bloat the docs. The tables are concise and should contain all required information.

Added info about pagination

---

apiary.apib

When generating Python code for example from requests the header `X-Acrolinx-Auth` is also there with a placeholder value `your_access_token`, indicating the API user to replace with the actual API token.
**Adds:**
- Add missing `+ Headers` section with `X-Acrolinx-Auth: your_access_token` to the following sections:
- User API
- Role API
- Checking API
-  Add both `X-Acrolinx-Auth: your_access_token` and `X-Acrolinx-Client: your_client_signature` (Fox checking API the client signature also required)
**Example:**
**Fixes:**
- Some URI parameters not showing up (for Group Role API, some checking API, ..)
- Also URI parameter description should be added after `-` (replaced `...`)
- URI parameters should be under sections, not `+ Request` (See Parent sections: …

DEV-26948 Add missing auth headers to requests

---

apiary.apib

- Add note about `prev` and `next` being omitted when those pages do not exist
- Add 400 response error when `per_page` exceeds max of 500 (or is not between 1 and 500)

DEV-27221: User API pagination update

---

apiary.apib

The User API returns the user data including the associated roles. However,  Roles can contain multiple privileges and are used to assign a set of privileges to users but in the User API when the client requests information about the user this transitive relation is not being populated. Instead only the associated roles are returned for each user in the response. 
Now we have removed this quite confusing empty privileges array from the User response model under the `/api/v1/users` route. 
```
// GetAllUsers - Before
{
"links": {},
"data": [
{
"id": "6b0cafac-04db-4e43-9ea8-dcd2b756574d",
"username": "termcontribution",
"fullName": "",
"createdOn": "2021-02-23T08:38:47.500Z",
"activeTokenId": "",
"lastIntegrationAccess": "1970-01-01T00:00:00Z",
"licenseType": "builtin",
"licenseStatus": …
```

DEV-26982 Remove empty privileges array from User response

---

apiary.apib

Add a call to the User API which allows requesting an update for users' custom fields. 
Note: This call requires the `UserAndRoles.editUser` privilege from the client.
+ Documented under the `User Commands` group
+ Added section for request `Request actualize Custom field values (for single user)`
+ Example request and response
+ Documented under the `User Bulk Opreations` group
+ Added section for request `Request actualize Custom field values in Bulk (for multiple users)`
+ Example request and response

DEV-27630 Document User API endpoint(s) for request user(s) to update custom field value

---

apiary.apib

- Add API to delete users in bulk

DEV-27677 I can delete users in bulk

---

apiary.apib

This adds a list of special characters that are allowed to be used when sorting custom fields. Note that this restrictions is only for sorting the custom fields. It does not put any restrictions on creating custom fields with other special characters not in the list.

DEV-27658: allowed special characters in custom field keys

---

apiary.apib

Edits from docs team

---

apiary.apib

Added a small description when sorting by `customFields` and some values are empty

DEV-27658 Replace null custom field value with empty string

---

doc/example-entry.actif.xml
term-api.md

* Terminology API documentation is referencing a sample ACTIF term file in the "create term entries" section
* this ACTIF file is now added (to the `doc/` subfolder)

term API doc: added referenced ACTIF sample file

---

apiary.apib

This PR updates the documentation on sorting. The sort results are additionally sorted by `username` field if not the sort parameter value.

DEV-27981 Sorting of one column will sort by username within the selected column

---

apiary.apib

The PR addresses the missing query parameters in the links section of the `getUsers()` API.

DEV-28595 Paginated requests include all query params in link section

---

apiary.apib

Add documentation about what values to use for CheckRequest.language, extend description of the default.

Extend documentation of CheckRequest.language

---

apiary.apib

Documents User API helper endpoint, provides a way to query users with missing required custom fields.
Add section `## Missing Required User Custom Fields`
+ `### Count Users [HEAD /api/v1/user/custom-fields-missing]`
+ `### Get Users [GET /api/v1/user/custom-fields-missing{?page,per_page}]`
**Visual preview:**

DEV-28754 Query users with missing required custom fields

---

apiary.apib

Add 2 sections under **Group Monitoring API**
- Get Health Status `GET /api/v1/monitoring/health/status`
- Get Health Liveliness `GET /api/v1/monitoring/health/live`
- Add success responses
- Add error response only to health status (it can return `503`)
- Error for health life means anything you get that is not `200`

docs: add section for health/status end point

---

apiary.apib

Since 2022.10 Acrolinx returns a guidelineId for
issues. This commit adds this field to the examples.

Add guidelineId to issues in examples

---

apiary.apib

In this case, the external authentication system is used to manage password change

docs: error response when external auth is enabled

---

apiary.apib

If you test this response example given in the document in a JSON validator it says that is invalid. The other response example above has "locales" as array. So, in this 2nd example it should be also an array.

fix: Locales is an array

---

apiary.apib

The delete role API returns with 204 (No Content) therefore the content-type (application/json) not needed there.

fix: Remove content type from a Delete Role response example returns with 204

---

apiary.apib

The given JSON response example for the Retrieve Platform Notifications request is invalid. Removed the extra curly bracket and re-formatted the example.

fix: Invalid JSON in response example for Retrieve Platform Notifications 

---

apiary.apib

For the Get Custom Fields request-response example it returns with an array of CustomField type objects in the data. Also use [fixed-type](https://apiblueprint.org/documentation/mson/specification.html#353-type-attribute) in array.

fix: Use array with fixed type CustomField type specification

---

apiary.apib

Resolve comment https://github.com/acrolinx/platform-api/pull/135#discussion_r1354566258
In context this should be clear its necessary for the action. I think its safe to remove.

docs: Remove note about valid access token needed

---

apiary.apib

Some conflicts were resolved that are blocking PR to actualize main from develop.

Resolve conflicts with main

---

.gitignore
apiary.apib

Reverts acrolinx/platform-api#139
I used the wrong branch. It should go into `develop`.

Revert "Resolve merge conflicts with `main`"

---

apiary.apib

Fix the provided example for Create a dictionary entry in the Dictionary API group. When a new entry has been created the success response status code is 201 and the type (application/json).

fix: Create a dictionary entry success response example

---

apiary.apib

Removed deleted `referennce` and `contentType` fields from response data and added missing Parameters block for define the id param.

fix: Get Document by id example

---

apiary.apib

Noticed there is a tenantId field in the User API response/request examples, but in reality this API not has this field.

Remove tenantId from User API examples

---

apiary.apib

Updated the docs about the latest changes relating to error messages in the User API.
The error messages haven't fundamentally changed. In most cases, the documentation still matches. 
Some `title` and `detail` fields have been localized. But since the translations are still work in progress and they're likely to change, I haven't updated the examples. The hard-coded messages are good enough and they should be the fallback anyway. 
Shortened the list of validation errors, since we were explaining all kinds of errors from validation in the code but neglected the bean validation. I think a condensed example is enough. 
Added examples of errors on token creation by/for built-in `admin` user and privilege escalation error.

Document new error messages from User API

---

.gitlab-ci.yml

Installing `apiaryio` with `gem install` is failing on GitLab. Suggested solution is to update the Ruby version >= 2.7.0.
Error message
```
ERROR:  Error installing apiaryio:
The last version of domain_name (~> 0.5) to support your Ruby & RubyGems was 0.5.20190701. Try installing it with `gem install domain_name -v 0.5.20190701` and then running the current command again
domain_name requires Ruby version >= 2.7.0. The current ruby version is 2.6.5.114.
```

fix: Bump Ruby version 2.7.0

---

apiary.apib

Due to a change in functionality, invalid tokens no longer result in a 401 response on the index/root API, and are instead ignored.
This updates the related docs to remove the comment about invalid tokens resulting in a 401.

Remove the comment about invalid tokens resulting in a 401 on the index/root API

---

apiary.apib

This adds:
- The new `idpUser`, `staffUser` and `rolesSetByIdp` properties to the user json.
- The 400 response when attempting to update a user's roles when they are managed by their identity provider.

Add new docs from Acrolinx One GA updates

---

.gitlab-ci.yml
apiary.apib

- bump the ruby version to 3.3
- separate group for reporting API

fix: bump the ruby version to 3.3 and separate group for reporting API

---

apiary.apib

Add documentation:
- Link to authorization and authentication to get the access token
- How to access reporting API using cURL
- Restriction on days limit per request

feat: add documentation for cURL access, Acrolinx access token, days limit

---

apiary.apib

Revert changes to remove messages for not provided dates. This message is required to let user know that the start or end date is not provided. Add message again which is removed in last commit.

feat: add message for empty start and end date

---

apiary.apib

Remove incorrect response from concurrent request description.
The actual response message `Too many requests. Try again later. If you still have trouble, contact Acrolinx Support.` (provided by UX team) is already present in the Response section for both checks and issues API.

refactor: remove incorrect response message

---

apiary.apib

Up to now, the Index endpoint only returned the platform version. Starting with 2024.09 it also contains version info about the linguistic configuration that is installed for that platform.

Add example for version info about linguistic configuration

---

apiary.apib

1. Added link to check types info.
2. Add check type documentation in reporting API.

Add check type documentation in reporting API

---

apiary.apib

For CSV format rename goal column to 'Goal ID' because Issue messages in pulsar contains goal ID and not the goal display name.

doc: rename goal column name to goal ID

---

apiary.apib

Rename `CSV` columns:
- target → Style guide
- target ID → Style guide ID
- Correctness → Spelling and grammar

feat: rename docs for checks csv column names

---

apiary.apib

The `POST /api/v1/roles` now rejects requests with role names containing semicolons

DEV-41288: Reject requests with role names containing semicolons

---

apiary.apib

This removes the `404` response from the DELETE user endpooint docs, as we now return `204` even if the user did not exist in the first place.

DEV-42450: Remove 404 response from delete user docs
