acrolinx/platform-api

apiary.apib
Documented the new monitoring API for 2019.10.
=> DEV-21564 documented monitoring API

README.md
The message conveyed by the two deleted sentences is already stated few lines above. IMO we don't need the two sentences
=> Removed redundant statements

apiary.apib
Adjusted reportTypes to have existing values.
=> checking/capabilities: Adjusted reportTypes

apiary.apib
=> Added `defaultGuiddanceProfileId` to capabilities

apiary.apib
a new link is available, which saves an additional request.
=> add new report type for content analysis dashboard

apiary.apib
As requested in DEV-19514, no more mentioning of the term harvesting report.
=> Removed references to term harvesting report.

apiary.apib
Reverted removal of TH report documentation. 
It turned out that the removal was requested accidentally in the first place.
=> Revert "Removed references to term harvesting report."

apiary.apib
* make goals consistent
* use goals from Targets
* documented new attributes
* fixed attribute names and values
=> fixed and extended the sample check result

apiary.apib
- Make sure the response examples for the user resource is consistent across the different HTTP methods `GET` and `PUT`
- Add missing fields like `"links": {}` from user and error responses
- Format white space to make linter happy
=> DEV-25704 standardized user response and error examples

apiary.apib
- Add `apib` data structure for User
- Add `apib` data structure for CustomField
=> DEV-25704 add data structure for user and custom field

apiary.apib
Added Update Role section with seprated requests
+ Request Update name
+ Request Update belonging privileges
=> DEV-25768 Added change the name of a role

apiary.apib
- Add section on deleting a role
- Add responses
- 204
- 400
- 401
- 404
- 409
=> DEV-25735 add DELETE role section with 204 response

apiary.apib
Added Request Update full name to Update User section
- with note, it can be also cleared (set empty)
=> DEV-25737 Added Request Update full name to Update User section

apiary.apib
- Add error responses
- 401
- 403
- 404
=> DEV-25719 add 401,403,404 responses

apiary.apib
Ref: DEV-26183
Add the missing JSON error responses. Mostly 403, 404
=> DEV-26183 docs/add json error responses

apiary.apib
I hope the structure with multiple requests is ok. I tested it locally and it looked fine.
=> Added request description how to update roles

apiary.apib
- add request api to create a new user
- with specified roles
- without any roles
- add responses
- 201
- 400
- 401
- 403
- 409
- 500
=> DEV-25720 add create user request and responses

apiary.apib
- Remove path parameter for user resource POST request
- Fix some typos
=> DEV-25720 minor changes

apiary.apib
Added a new group/section with name `User commands` under the `User API` group.
- Request: Release an Active Named User license [PUT /api/v1/user/{id}/_release]
- Responses: 204 - Success, 401,403,404 - Errors
=> DEV-25770 I can release an active named user license

apiary.apib
Added a missing request URI (but derived from the parent group) to the request `Create an API Token for User(s)`
=> DEV-25773 Add missing request path

apiary.apib
+ Added request: Create a user (Only the very basic user data)
+ Added request: Create a user with specified license type
+ Added DataStructure: CreateUser
+ Removed request: Create a user with default roles (Due to its same as the create user with basic fields or with specified license type, emphasized multiple times in the notes how it works and its optional)
=> Edited Create User section

apiary.apib
- Add `activeTokenId` to data structure
- Add `activeTokenId` to responses concerning users
=> add activeTokenId field to user responses

apiary.apib
- Add `UserStatus` enum in data structure
- Add `checkingFrequency` attribute in all user model responses
=> DEV-26342: add checkingFrequency in all user model responses

apiary.apib
+ Addded Export API to the User command group: 
+ Added request: `Export Users in CSV format [GET /api/v1/user/_export]` with
+ Accept: text/csv
+ Request description, CSV file formatting info and exported User fields summary
+ Response codes: (200, 401, 403)
+ Example response body and headers
+ Added requiest `Try Export Users with an unsupported media type`
+ Accept: `text/hmtl`
+ Error response JSON
+ Response code: 406
Plus note about `Content-Disposition` header to treat returned content as attachment and the file name formatting is: `acrolinx_users_export_yyyyMMdd_HHmmss.csv`
=> DEV-26311 Export and download Users data as a CSV file

apiary.apib
- Add optional `sort` query param to get all users section
=> DEV-25706: add optional sort query parameter to get all users section

apiary.apib
=> Docs/dev 26311 Enrich exported users data with license status

apiary.apib
Add comment on encoding query parameters
=> DEV-25706: add caution note on URI encoding

apiary.apib
Reviewed docs in apiary and made a few final updates
=> Final ux-writers-edits

apiary.apib
Added note about the underlying data source changing while calling the pagination api.
=> docs: add note on data source change during pagination call

apiary.apib
Document the possibility to set the user custom fields on user creation via `/api/v1/user` API.
**Note**: This PR should be held back until the .09 release. This feature will be available in the next release only. 
- Can be merged after: https://github.com/acrolinx/platform-api/pull/71
**Screenshot:**
How to find in the rendered doc:
=> DEV-26981 Create user with custom field values

apiary.apib
The user api needs to provide the possibility to sort the license type column also by status
=> DEV-27807 Allow correct sorting by license status if the user has the license type Named user

apiary.apib
Update docs with more friendly error message when creating or editing user then assigning more privileges than the current user
=> DEV-26980 Improve error response

apiary.apib
Update documentation on the possibility to search users by username and full name
=> DEV-26949 Search users by username and full name

apiary.apib
This PR adds documentation on get-all-users API filtering by roles ids
=> DEV-28180 User API filtering by role IDs

apiary.apib
Add sort notes on other sortable columns
=> DEV-27981 Sorting of one column will sort by username within the selected column

apiary.apib
The privilege for users' export has been updated to `editUser`
=> DEV-28482 Adjust privilege requirements for exporting the list of users

apiary.apib
- Add password requirements to create user section
- Add version number of when new requirements start
- Add note that older version have different requirement
- Update error response to show the 2 different error responses for the 2 different versions
- Update error response in the Bulk Create request
=> DEV-28242: add password requirements

apiary.apib
Made a few small changes to description text
=> Small tweaks for apiary docs

apiary.apib
- Add section under Users for random password generation
- Note on the requirements
- Note on the privileges
=> DEV-28485: add section on random password generation

apiary.apib
Add documentation on custom fields API
=> DEV-29043 Custom Field API to get defined user custom fields

apiary.apib
=> Edits to custom fields API text

apiary.apib
- Add error responses for invalid `page` parameters
- Add these to the get all users api
- Add these to the get custom fields missing api
=> DEV-29342: update pagination params error responses

apiary.apib
We introduced features for the User API get all users endpoint. These additional query params `exludeProperties` and `includeCustomField` can help optimize requests.
=> docs: Get all users include/exclude nested data

apiary.apib
Resolved some merge conflicts about blanks.
=> Resolve merge conflicts

apiary.apib
As requested, let's update the `develop` branch right away to `main`.
=> Update the `develop`-branch

apiary.apib
This adds some API error documentation for when a user update request is made that includes some roles that do not exist.
=> DEV-37012: Add docs for error when updating a user with non-existent roles

apiary.apib
This adds info on the new excludeCustomFields param to the API docs.
=> DEV-36440 exclude custom fields param

apiary.apib
We mistakenly merged the last change to main instead of develop.
=> Update develop with the latest from main branch

apiary.apib
This updates the comment in the API token creation error to reflect the new change related to privilege escalation.
=> Update comment to reflect new change in api token creation

term-api.md
https://acrolinx.atlassian.net/browse/DEV-30684
=> DEV-30684 update Term API docs

apiary.apib
Add documentation for CSV fields and note for reason behind empty csv
=> feat: add documentation for CSV fields and note

apiary.apib
Add documentation for escaping special characters in JSON.
=> doc: add json escape character info

.gitlab-ci.yml, apiary.apib
The ruby version 3.3 is pulling latest image ruby:3.3.6. 
Keep the ruby version 3.3.5.
=> Fix: ruby version 3.3.5

apiary.apib
- `reporting-api`: add documentation for `json` format 
- Remove duplicate documentation for `JSON - Escape special characters`
=> doc: json format documentation

README.md
This PR makes changes (review comments) suggested by Madeline in PR https://github.com/acrolinx/platform-api/pull/199.
=> doc: incorporate review comments

.gitlab-ci.yml, README.md, apiary.apib
Unfortunately this has conflicts https://github.com/acrolinx/platform-api/pull/191 and both are protected branches so unable to resolve the conflict directly in develop.
--------------------------------------------------------------------------------------------------------------------------------
The changes are merged from both main and develop branches in this branch.
- Reporting-api documentation:
- feature to download data in json format
- term related fields in report
- Goal id and goal names (only in English language) in data
- Update instructions in readme file
- Remove duplicate documentation about json special character
- docs: Update index response with new platform / core version structure
- docs: Add new versions + guidance package section to 200 response
- remove dictionary …
=> Resolve conflict branch develop to main

apiary.apib
Add description for goal name field in reporting-api documentaion.
=> feat: add documention for goal name

apiary.apib
- Add doc for UTC date time format
- Correct type, limit and order of fields in `reporpting-api` documentation
=> feat: add UTC format info and correct data types/limit for fields

README.md
Fixed some linting issues like line-length and extra newlines around lists.
=> Fix README linting issues

apiary.apib
The apib file had missing parameters/examples in order to match the apib spec.
Added the missing parameters and added examples as needed.
Updated the parameter type definitions to match the spec.
=> Updated apib definition to match the spec
